# 1.Numpy

In [1]:
import numpy as np

In [4]:
array = np.array([[1,2,3],[2,3,4]])
array

array([[1, 2, 3],
       [2, 3, 4]])

In [6]:
array.ndim

2

In [7]:
array.shape

(2, 3)

In [8]:
array.size

6

In [9]:
type(array)

numpy.ndarray

In [10]:
np.array([2,23,4])

array([ 2, 23,  4])

In [11]:
a = np.array([2,23,4],dtype=np.int)
a.dtype

dtype('int32')

In [14]:
a = np.array([2,23,4],dtype=np.float)
a.dtype

dtype('float64')

In [21]:
b = np.array([[2,3,4],[1,2,3]])
print(b)

[[2 3 4]
 [1 2 3]]


In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones((2,3),dtype=np.float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [29]:
np.arange(12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [30]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [31]:
np.linspace(1,10,20).reshape(5,4)

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105,  3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789,  5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474,  7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [32]:
a = np.array([10,20,30,40])
b = np.arange(4)
print(a)
print(b)

[10 20 30 40]
[0 1 2 3]


In [35]:
c=a-b
c

array([10, 19, 28, 37])

In [36]:
c=a+b
c

array([10, 21, 32, 43])

In [37]:
c=a*b
c

array([  0,  20,  60, 120])

In [38]:
c = b**2
c

array([0, 1, 4, 9], dtype=int32)

In [39]:
c = 10*np.sin(a)
c

array([-5.44021111,  9.12945251, -9.88031624,  7.4511316 ])

In [40]:
b<3

array([ True,  True,  True, False])

In [45]:
a = np.array([[1,1,],[0,1]])
b = np.arange(4).reshape(2,2,)
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [47]:
c_dot = np.dot(a,b)
c_dot

array([[2, 4],
       [2, 3]])

In [48]:
c_dot = a.dot(b)
c_dot

array([[2, 4],
       [2, 3]])

In [60]:
a = np.random.random((2,4))
a

array([[0.92015882, 0.71364892, 0.56412239, 0.15954239],
       [0.37080869, 0.42618279, 0.81010071, 0.6374066 ]])

In [61]:
np.sum(a)

4.60197130527387

In [62]:
np.min(a)

0.15954238673578436

In [63]:
np.max(a)

0.9201588233058513

In [64]:
np.sum(a,axis=0)

array([1.29096751, 1.13983171, 1.37422309, 0.79694899])

In [65]:
np.sum(a,axis=1)

array([2.35747252, 2.24449879])

In [66]:
np.min(a,axis=0)

array([0.37080869, 0.42618279, 0.56412239, 0.15954239])

In [67]:
np.min(a,axis=1)

array([0.15954239, 0.37080869])

In [68]:
a = np.arange(2,14).reshape((3,4))
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [69]:
np.argmax(a)

11

In [70]:
np.argmin(a)

0

In [71]:
np.mean(a)

7.5

In [72]:
np.average(a)

7.5

In [73]:
a.mean()

7.5

In [75]:
a.cumsum()

array([ 2,  5,  9, 14, 20, 27, 35, 44, 54, 65, 77, 90], dtype=int32)

In [76]:
np.diff(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [77]:
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [78]:
np.nonzero(a)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [79]:
a = np.arange(14,2,-1).reshape((3,4))
a

array([[14, 13, 12, 11],
       [10,  9,  8,  7],
       [ 6,  5,  4,  3]])

In [80]:
np.sort(a)

array([[11, 12, 13, 14],
       [ 7,  8,  9, 10],
       [ 3,  4,  5,  6]])

In [83]:
np.transpose(a)

array([[14, 10,  6],
       [13,  9,  5],
       [12,  8,  4],
       [11,  7,  3]])

In [84]:
a.T

array([[14, 10,  6],
       [13,  9,  5],
       [12,  8,  4],
       [11,  7,  3]])

In [85]:
np.clip(a,5,9)

array([[9, 9, 9, 9],
       [9, 9, 8, 7],
       [6, 5, 5, 5]])

In [87]:
a = np.arange(3,15)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [88]:
a[4]

7

In [91]:
b = a.reshape(3,4)
b

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [92]:
b[2]

array([11, 12, 13, 14])

In [95]:
b[1][1]

8

In [96]:
b[1,1]

8

In [98]:
b[1,1:3]

array([8, 9])

In [107]:
for row in b:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [110]:
for column in b.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [112]:
b

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [113]:
b.flatten()

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [114]:
for item in b.flat:
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14


In [115]:
a = np.array([1,1,1])
b = np.array([2,2,2])
np.vstack((a,b))

array([[1, 1, 1],
       [2, 2, 2]])

In [117]:
np.hstack((a,b))

array([1, 1, 1, 2, 2, 2])

In [131]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [132]:
np.split(a,2,axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [133]:
np.split(a,3,axis=0)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [134]:
np.array_split(a,3,axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2],
        [ 6],
        [10]]), array([[ 3],
        [ 7],
        [11]])]

In [135]:
np.vsplit(a,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [137]:
np.hsplit(a,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [150]:
a = np.arange(4)
b = a
c = a
d = c
print(a)
print(b)
print(c)
print(d)

[0 1 2 3]
[0 1 2 3]
[0 1 2 3]
[0 1 2 3]


In [151]:
b is a

True

In [152]:
c is a

True

In [153]:
d is a

True

In [156]:
a[0] = 11
a

array([11,  1,  2,  3])

In [157]:
b

array([11,  1,  2,  3])

In [158]:
c

array([11,  1,  2,  3])

In [159]:
d[1:3] = [2,3]

In [160]:
a

array([11,  2,  3,  3])

In [161]:
b = a.copy()
b is a

False

# 2.Pandas

In [164]:
import pandas as pd
import numpy as np
s = pd.Series([1,3,6,np.nan,44,1])
print(s)

0     1.0
1     3.0
2     6.0
3     NaN
4    44.0
5     1.0
dtype: float64


In [171]:
dates = pd.date_range('20160101',periods=6)
df = pd.DataFrame(np.random.randn(6,4),index = dates,columns=('a','b','c','d'))
df

a         b         c         d
2016-01-01 -1.917930 -0.665193  1.815398 -2.066365
2016-01-02 -0.279379  0.972623  0.526810  0.904660
2016-01-03  0.364895 -1.092709 -0.924056  0.592086
2016-01-04 -0.617103 -0.306446 -2.116430  0.391049
2016-01-05  0.461686  0.422426  0.044861  1.139181
2016-01-06 -0.617084 -0.004054  0.680138 -1.869349

In [172]:
df['b']

2016-01-01   -0.665193
2016-01-02    0.972623
2016-01-03   -1.092709
2016-01-04   -0.306446
2016-01-05    0.422426
2016-01-06   -0.004054
Freq: D, Name: b, dtype: float64

In [174]:
df = pd.DataFrame(np.arange(12).reshape(3,4))
df

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [176]:
df2 = pd.DataFrame({'A' : 1.,
                    'B' : pd.Timestamp('20130102'),
                    'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                    'D' : np.array([3] * 4,dtype='int32'),
                    'E' : pd.Categorical(["test","train","test","train"]),
                    'F' : 'foo'})
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [177]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [178]:
df2.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [179]:
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [180]:
df2.values

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [181]:
df2.describe()

A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0

In [183]:
df2.T

0                    1                    2  \
A                    1                    1                    1   
B  2013-01-02 00:00:00  2013-01-02 00:00:00  2013-01-02 00:00:00   
C                    1                    1                    1   
D                    3                    3                    3   
E                 test                train                 test   
F                  foo                  foo                  foo   

                     3  
A                    1  
B  2013-01-02 00:00:00  
C                    1  
D                    3  
E                train  
F                  foo

In [185]:
datas = pd.date_range('20160101',periods=6)
df = pd.DataFrame(np.arange(24).reshape(6,4),index=datas,columns=['A','B','C','D'])
df

A   B   C   D
2016-01-01   0   1   2   3
2016-01-02   4   5   6   7
2016-01-03   8   9  10  11
2016-01-04  12  13  14  15
2016-01-05  16  17  18  19
2016-01-06  20  21  22  23

In [186]:
df['A']

2016-01-01     0
2016-01-02     4
2016-01-03     8
2016-01-04    12
2016-01-05    16
2016-01-06    20
Freq: D, Name: A, dtype: int32

In [187]:
df[0:3]

A  B   C   D
2016-01-01  0  1   2   3
2016-01-02  4  5   6   7
2016-01-03  8  9  10  11

In [188]:
df

A   B   C   D
2016-01-01   0   1   2   3
2016-01-02   4   5   6   7
2016-01-03   8   9  10  11
2016-01-04  12  13  14  15
2016-01-05  16  17  18  19
2016-01-06  20  21  22  23

In [189]:
df.loc['20160102']

A    4
B    5
C    6
D    7
Name: 2016-01-02 00:00:00, dtype: int32

In [200]:
df.loc[:,['A','B']]

A   B
2016-01-01   0   1
2016-01-02   4   5
2016-01-03   8   9
2016-01-04  12  13
2016-01-05  16  17
2016-01-06  20  21

In [201]:
df.iloc[3,1]

13

In [202]:
df.iloc[3:5,1:3]

B   C
2016-01-04  13  14
2016-01-05  17  18

In [206]:
df.loc['20160101':'20160103',['A','C']]

A   C
2016-01-01  0   2
2016-01-02  4   6
2016-01-03  8  10

In [207]:
dates = pd.date_range('20120101',periods=6)
df = pd.DataFrame(np.arange(24).reshape(6,4),index=dates,columns=['A','B','C','D'])
df

A   B   C   D
2012-01-01   0   1   2   3
2012-01-02   4   5   6   7
2012-01-03   8   9  10  11
2012-01-04  12  13  14  15
2012-01-05  16  17  18  19
2012-01-06  20  21  22  23

In [213]:
df.iloc[2,2]=111
df

A   B    C   D
2012-01-01   0   1    2   3
2012-01-02   4   5    6   7
2012-01-03   8   9  111  11
2012-01-04  12  13   14  15
2012-01-05  16  17   18  19
2012-01-06  20  21   22  23

In [219]:
df.B[df.A>0]=0
df

A  B    C   D
2012-01-01   0  1    2   3
2012-01-02   4  0    6   7
2012-01-03   8  0  111  11
2012-01-04  12  0   14  15
2012-01-05  16  0   18  19
2012-01-06  20  0   22  23

In [226]:
df['F'] = np.NAN
df

A  B    C   D   F
2012-01-01   0  1    2 NaN NaN
2012-01-02   4  0    6 NaN NaN
2012-01-03   8  0  111 NaN NaN
2012-01-04  12  0   14 NaN NaN
2012-01-05  16  0   18 NaN NaN
2012-01-06  20  0   22 NaN NaN

In [229]:
df['E'] = pd.Series([1,2,3,4,5,6], index=pd.date_range('20130101',periods=6))
df

A  B    C   D   F   E
2012-01-01   0  1    2 NaN NaN NaN
2012-01-02   4  0    6 NaN NaN NaN
2012-01-03   8  0  111 NaN NaN NaN
2012-01-04  12  0   14 NaN NaN NaN
2012-01-05  16  0   18 NaN NaN NaN
2012-01-06  20  0   22 NaN NaN NaN

In [230]:
dates = pd.date_range('20130101', periods=6)
df = pd.DataFrame(np.arange(24).reshape((6,4)),index=dates, columns=['A','B','C','D'])
df.iloc[0,1] = np.nan
df.iloc[1,2] = np.nan

In [231]:
df

A     B     C   D
2013-01-01   0   NaN   2.0   3
2013-01-02   4   5.0   NaN   7
2013-01-03   8   9.0  10.0  11
2013-01-04  12  13.0  14.0  15
2013-01-05  16  17.0  18.0  19
2013-01-06  20  21.0  22.0  23

In [234]:
df.iloc[1:3,0:3]

A    B     C
2013-01-02  4  5.0   NaN
2013-01-03  8  9.0  10.0

In [236]:
df.dropna(axis=0,how='any')

A     B     C   D
2013-01-03   8   9.0  10.0  11
2013-01-04  12  13.0  14.0  15
2013-01-05  16  17.0  18.0  19
2013-01-06  20  21.0  22.0  23

In [238]:
df.fillna(value=0)

A     B     C   D
2013-01-01   0   0.0   2.0   3
2013-01-02   4   5.0   0.0   7
2013-01-03   8   9.0  10.0  11
2013-01-04  12  13.0  14.0  15
2013-01-05  16  17.0  18.0  19
2013-01-06  20  21.0  22.0  23

In [239]:
df.isnull()

A      B      C      D
2013-01-01  False   True  False  False
2013-01-02  False  False   True  False
2013-01-03  False  False  False  False
2013-01-04  False  False  False  False
2013-01-05  False  False  False  False
2013-01-06  False  False  False  False

In [242]:
data = pd.read_csv("student.csv")

In [243]:
data

Student ID  name   age  gender
0         1100  Kelly   22  Female
1         1101    Clo   21  Female
2         1102  Tilly   22  Female
3         1103   Tony   24    Male
4         1104  David   20    Male
5         1105  Catty   22  Female
6         1106      M    3  Female
7         1107      N   43    Male
8         1108      A   13    Male
9         1109      S   12    Male
10        1110  David   33    Male
11        1111     Dw    3  Female
12        1112      Q   23    Male
13        1113      W   21  Female

In [245]:
df1 = pd.DataFrame(np.ones((3,4))*0, columns=['a','b','c','d'])
df2 = pd.DataFrame(np.ones((3,4))*1, columns=['a','b','c','d'])
df3 = pd.DataFrame(np.ones((3,4))*2, columns=['a','b','c','d'])
print(df1)
print(df2)
print(df3)

     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
     a    b    c    d
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0
     a    b    c    d
0  2.0  2.0  2.0  2.0
1  2.0  2.0  2.0  2.0
2  2.0  2.0  2.0  2.0


In [246]:
result = pd.concat([df1,df2,df3],axis=0)
result

a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0
0  2.0  2.0  2.0  2.0
1  2.0  2.0  2.0  2.0
2  2.0  2.0  2.0  2.0

In [247]:
result = pd.concat([df1,df2,df3],axis=1)
result

a    b    c    d    a    b    c    d    a    b    c    d
0  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  2.0  2.0  2.0  2.0
1  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  2.0  2.0  2.0  2.0
2  0.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0  2.0  2.0  2.0  2.0

In [249]:
result = pd.concat([df1,df2,df3],axis=0,ignore_index=True)
result

a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0
6  2.0  2.0  2.0  2.0
7  2.0  2.0  2.0  2.0
8  2.0  2.0  2.0  2.0

In [250]:
df1 = pd.DataFrame(np.ones((3,4))*0, columns=['a','b','c','d'], index=[1,2,3])
df2 = pd.DataFrame(np.ones((3,4))*1, columns=['b','c','d','e'], index=[2,3,4])
df1

a    b    c    d
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0

In [251]:
df2

b    c    d    e
2  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0

In [252]:
result2 = pd.concat([df1,df2],axis=0,join='outer')
result2

a    b    c    d    e
1  0.0  0.0  0.0  0.0  NaN
2  0.0  0.0  0.0  0.0  NaN
3  0.0  0.0  0.0  0.0  NaN
2  NaN  1.0  1.0  1.0  1.0
3  NaN  1.0  1.0  1.0  1.0
4  NaN  1.0  1.0  1.0  1.0

In [254]:
result3 = pd.concat([df1,df2],axis=0,join='inner')
result3

b    c    d
1  0.0  0.0  0.0
2  0.0  0.0  0.0
3  0.0  0.0  0.0
2  1.0  1.0  1.0
3  1.0  1.0  1.0
4  1.0  1.0  1.0

In [255]:
df1 = pd.DataFrame(np.ones((3,4))*0, columns=['a','b','c','d'])
df2 = pd.DataFrame(np.ones((3,4))*1, columns=['a','b','c','d'])
df3 = pd.DataFrame(np.ones((3,4))*1, columns=['a','b','c','d'])
s1 = pd.Series([1,2,3,4], index=['a','b','c','d'])

In [256]:
res = df1.append(df2, ignore_index=True)
res

a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0

In [259]:
res = df1.append([df2, df3], ignore_index=True)
print(res)
s1

     a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  1.0  1.0  1.0  1.0
4  1.0  1.0  1.0  1.0
5  1.0  1.0  1.0  1.0
6  1.0  1.0  1.0  1.0
7  1.0  1.0  1.0  1.0
8  1.0  1.0  1.0  1.0


a    1
b    2
c    3
d    4
dtype: int64

In [258]:
res = df1.append(s1, ignore_index=True)
res

a    b    c    d
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0
3  1.0  2.0  3.0  4.0

In [260]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                             'A': ['A0', 'A1', 'A2', 'A3'],
                             'B': ['B0', 'B1', 'B2', 'B3']})
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                              'C': ['C0', 'C1', 'C2', 'C3'],
                              'D': ['D0', 'D1', 'D2', 'D3']})
left

A   B key
0  A0  B0  K0
1  A1  B1  K1
2  A2  B2  K2
3  A3  B3  K3

In [262]:
right

C   D key
0  C0  D0  K0
1  C1  D1  K1
2  C2  D2  K2
3  C3  D3  K3

In [265]:
result =  pd.merge(left,right,on='key')
result

A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3

In [266]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                      'key2': ['K0', 'K1', 'K0', 'K1'],
                      'A': ['A0', 'A1', 'A2', 'A3'],
                      'B': ['B0', 'B1', 'B2', 'B3']})
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                       'key2': ['K0', 'K0', 'K0', 'K0'],
                       'C': ['C0', 'C1', 'C2', 'C3'],
                       'D': ['D0', 'D1', 'D2', 'D3']})


In [267]:
left

A   B key1 key2
0  A0  B0   K0   K0
1  A1  B1   K0   K1
2  A2  B2   K1   K0
3  A3  B3   K2   K1

In [268]:
right

C   D key1 key2
0  C0  D0   K0   K0
1  C1  D1   K1   K0
2  C2  D2   K1   K0
3  C3  D3   K2   K0

In [273]:
result = pd.merge(left,right,on=['key1','key2'],how='inner')
result

A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
1  A2  B2   K1   K0  C1  D1
2  A2  B2   K1   K0  C2  D2

In [271]:
result = pd.merge(left,right,on=['key1','key2'],how='left')
result

A   B key1 key2    C    D
0  A0  B0   K0   K0   C0   D0
1  A1  B1   K0   K1  NaN  NaN
2  A2  B2   K1   K0   C1   D1
3  A2  B2   K1   K0   C2   D2
4  A3  B3   K2   K1  NaN  NaN

In [274]:
# 随机生成1000个数据
data = pd.Series(np.random.randn(1000),index=np.arange(1000))
 
# 为了方便观看效果, 我们累加这个数据
data.cumsum()

# pandas 数据可以直接观看其可视化形式
data.plot()

plt.show()

NameError: name 'plt' is not defined